# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:16
        # Provide the password for postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: 
          - 5432:5432

    steps:
      # Mengatur atau instalasi Go ke Runner
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.2'
      id: go

      # Memeriksa kode repositori ini ke Runner
    - name: Check out code into Go module directory 
      uses: actions/checkout@v3

      # Mendapatkan depedencies
      # Sebenarnya tidak membutuhkan ini karena Go Mod secara otomatis mengunduh package yang dipakai
    # - name: Get Depedencies
    #   run: |
    #     go get -v -t -d ./...
    #     if [-f Gopkg.toml]; then
    #         curl https://raw.githubusercontent.com/golang/dep/main/install.sh | sh
    #     fi

      # Build Golang
      # Tidak membutuhkan ini karena aplikasi akan secara otomatis di build saat test
    # - name: Build
    #   run: go build -v ./...

      # Install Go Migrate
    - name: Install Golang migrate
      # Lakukan Instalasi GO Migrate
      # Pindahkan migrate ke /user/bin/{ganti nama menjadi migrate karena harus disesuaikan dengan migrate}
      run: | 
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        which migrate

      # Lakukan migrasi DB
    - name: Migrate DB
      run: make migrateup

      # Test Golang
    - name: Test
      run: make gotest
